name: Build DROP App APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter Engine
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK File
        run: |
          flutter create drop_app
          cd drop_app
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK File
        uses: actions/upload-artifact@v4
        with:
          name: DROP-App-Release
          path: drop_app/build/app/outputs/flutter-apk/app-release.apk
